name: Android CI

on:
  push:
    branches: [ main, rewrite/clean-code-arc-mvvm+i ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create file
      run: cat ./app/google-services.json | base64
    - name: Putting data
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA > ./app/google-services.json
    - name: Build with Gradle
      run: ./gradlew build
